name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  create-deployment-artifans:
    name: Create Deployment Artifans
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
