name: Deploy Application

on:
  pull_request:
    branches:
      - main

jobs:
  create-deployment-artifans:
    name: Create Deployment Artifans
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure PHP 8.0
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.0
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml


      - name: Install Composer
        run: composer install --no-dev --no-interaction --prefer-dist

      -name: Run Tests
        run: php artisan test
